version: "3.3"
services:
  web:
    build: .
    ports:
      - "8069:8069"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: always 