# Generated by Django 4.2.1 on 2025-06-18 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contacts_user_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacts',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='main.message'),
        ),
        migrations.AddField(
            model_name='message',
            name='name',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
