# Generated by Django 5.0.6 on 2025-07-07 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emails',
            name='email',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.CharField(max_length=5500),
        ),
    ]
